const fs = require('fs');
const path = require('path');
const { Client } = require('pg');
const bcrypt = require('bcryptjs');
require('dotenv').config();

async function deploy() {
  console.log('Connecting to Supabase database...');
  const client = new Client({
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT, 10),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 15000
  });

  try {
    await client.connect();
    console.log('✅ Connected to Supabase!');

    // 1. Run Migrations
    const migrationsDir = path.join(__dirname, '../database/migrations');
    const migrationFiles = fs.readdirSync(migrationsDir)
      .filter(f => f.endsWith('.sql'))
      .sort();

    console.log('\n--- EXECUTING MIGRATIONS ---');
    for (const file of migrationFiles) {
      const filePath = path.join(migrationsDir, file);
      console.log(`Running migration: ${file}`);
      const sql = fs.readFileSync(filePath, 'utf8');
      await client.query(sql);
      console.log(`  └─ Done: ${file}`);
    }

    // 2. Run Initial Seeds (Geography, Agricultural Lookups, Schemes)
    console.log('\n--- EXECUTING BASE SEEDS ---');
    const initialSeeds = ['001_geography_seed.sql', '002_agricultural_lookup_seed.sql', '003_schemes_seed.sql'];
    for (const file of initialSeeds) {
      const filePath = path.join(__dirname, '../database/seeds', file);
      console.log(`Running seed: ${file}`);
      const sql = fs.readFileSync(filePath, 'utf8');
      await client.query(sql);
      console.log(`  └─ Done: ${file}`);
    }

    // 3. Generate Groundwater Assessment Seed Matching Actual DB Districts/Villages
    console.log('\n--- GENERATING GROUNDWATER ASSESSMENTS SEED ---');
    const districtsRes = await client.query('SELECT district_id FROM districts ORDER BY district_id');
    const villagesRes = await client.query('SELECT village_id, district_id FROM villages ORDER BY village_id');
    console.log(`Found ${districtsRes.rows.length} districts and ${villagesRes.rows.length} villages in Supabase.`);

    const years = [
      { year: '2023-2024', predicted: false },
      { year: '2024-2025', predicted: false },
      { year: '2025-2026', predicted: true },
      { year: '2026-2027', predicted: true }
    ];
    const categories = ['Safe', 'Semi Critical', 'Critical', 'Over Exploited', 'Saline', 'Hilly Area'];

    let sql = `-- Seed file generated by deploy_to_supabase.js\n`;
    sql += `TRUNCATE TABLE groundwater_assessments RESTART IDENTITY CASCADE;\n\n`;

    // Districts
    sql += `-- 1. District Level Groundwater Assessments\n`;
    sql += `INSERT INTO groundwater_assessments (district_id, assessment_year, is_predicted, extractable_resources_bcm, extraction_all_uses_bcm, rainfall_mm, recharge_bcm, natural_discharges_bcm, category)\nVALUES\n`;
    const districtLines = [];
    districtsRes.rows.forEach(d => {
      const dHash = d.district_id;
      years.forEach((yr, idx) => {
        const catIdx = (dHash + idx) % categories.length;
        const category = categories[catIdx];
        const rainfall = 500 + (dHash * 15 + idx * 30) % 600;
        const extractable = 1.0 + (dHash * 0.12 + idx * 0.05) % 2.0;
        let ratio = 0.4;
        if (category === 'Safe') ratio = 0.35 + (dHash % 15) / 100;
        else if (category === 'Semi Critical') ratio = 0.72 + (dHash % 15) / 100;
        else if (category === 'Critical') ratio = 0.92 + (dHash % 7) / 100;
        else if (category === 'Over Exploited') ratio = 1.25 + (dHash % 30) / 100;
        else if (category === 'Saline') ratio = 0.6 + (dHash % 20) / 100;
        else ratio = 0.2;
        const extraction = extractable * ratio;
        const recharge = extractable * 1.1;
        const naturalDischarges = recharge * 0.09;
        districtLines.push(`    (${d.district_id}, '${yr.year}', ${yr.predicted}, ${extractable.toFixed(2)}, ${extraction.toFixed(2)}, ${rainfall.toFixed(2)}, ${recharge.toFixed(2)}, ${naturalDischarges.toFixed(2)}, '${category}')`);
      });
    });
    sql += districtLines.join(',\n') + ';\n\n';

    // Villages
    sql += `-- 2. Village Level Groundwater Assessments\n`;
    sql += `INSERT INTO groundwater_assessments (village_id, assessment_year, is_predicted, extractable_resources_bcm, extraction_all_uses_bcm, rainfall_mm, recharge_bcm, natural_discharges_bcm, category)\nVALUES\n`;
    const villageLines = [];
    villagesRes.rows.forEach(v => {
      const vHash = v.village_id + v.district_id * 3;
      years.forEach((yr, idx) => {
        const catIdx = (vHash + idx) % categories.length;
        const category = categories[catIdx];
        const rainfall = 450 + (vHash * 8 + idx * 25) % 700;
        const extractable = 0.01 + (vHash * 0.002 + idx * 0.001) % 0.04;
        let ratio = 0.4;
        if (category === 'Safe') ratio = 0.4 + (vHash % 10) / 100;
        else if (category === 'Semi Critical') ratio = 0.75 + (vHash % 10) / 100;
        else if (category === 'Critical') ratio = 0.95 + (vHash % 5) / 100;
        else if (category === 'Over Exploited') ratio = 1.35 + (vHash % 25) / 100;
        else if (category === 'Saline') ratio = 0.55 + (vHash % 15) / 100;
        else ratio = 0.15;
        const extraction = extractable * ratio;
        const recharge = extractable * 1.1;
        const naturalDischarges = recharge * 0.09;
        villageLines.push(`    (${v.village_id}, '${yr.year}', ${yr.predicted}, ${extractable.toFixed(4)}, ${extraction.toFixed(4)}, ${rainfall.toFixed(2)}, ${recharge.toFixed(4)}, ${naturalDischarges.toFixed(4)}, '${category}')`);
      });
    });
    sql += villageLines.join(',\n') + ';\n';

    // Save regenerated seed file
    fs.writeFileSync(path.join(__dirname, '../database/seeds/004_groundwater_assessments_seed.sql'), sql, 'utf8');
    console.log('Saved updated 004_groundwater_assessments_seed.sql');

    // Execute groundwater assessments seed
    console.log('Running seed: 004_groundwater_assessments_seed.sql');
    await client.query(sql);
    console.log('  └─ Done: 004_groundwater_assessments_seed.sql');

    // 4. Create Default Test Users
    console.log('\n--- CREATING TEST USERS ---');
    const passwordHash = await bcrypt.hash('password123', 10);
    const SYSTEM_ROLES = ['VILLAGE_HEAD', 'AUDITOR', 'GOVERNMENT_EMPLOYEE', 'ADMIN'];

    for (const role of SYSTEM_ROLES) {
      const name = `Test ${role.replace('_', ' ').toLowerCase()}`;
      const email = `test_${role.toLowerCase()}@example.com`;
      const existing = await client.query('SELECT id FROM users WHERE email = $1', [email]);
      if (existing.rows.length === 0) {
        let villageId = null;
        let districtId = null;
        if (role === 'VILLAGE_HEAD') villageId = 1;
        if (role === 'AUDITOR') districtId = 1;

        await client.query(
          'INSERT INTO users (name, email, password_hash, role, village_id, district_id) VALUES ($1, $2, $3, $4, $5, $6)',
          [name, email, passwordHash, role, villageId, districtId]
        );
        console.log(`  └─ Created ${role} user (${email})`);
      }
    }

    // 5. Verification of Created Tables & Row Counts
    console.log('\n--- VERIFYING SUPABASE TABLES & ROW COUNTS ---');
    const tablesRes = await client.query(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `);

    for (const row of tablesRes.rows) {
      const tableName = row.table_name;
      const countRes = await client.query(`SELECT COUNT(*) FROM "${tableName}"`);
      console.log(`  • Table '${tableName}': ${countRes.rows[0].count} rows`);
    }

    console.log('\n🎉 ALL TABLES AND DATA SUCCESSFULLY DEPLOYED TO SUPABASE!');
  } catch (err) {
    console.error('❌ Migration failed:', err);
  } finally {
    await client.end();
  }
}

deploy();
