const fs = require('fs');
const path = require('path');
require('dotenv').config();
const { Client } = require('pg');

async function run() {
  const client = new Client({
    host: process.env.DB_HOST,
    port: process.env.DB_PORT ? parseInt(process.env.DB_PORT, 10) : 5432,
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
  });

  try {
    await client.connect();
    console.log('Connected to DB. Fetching districts and villages...');

    const districtsRes = await client.query('SELECT district_id, name FROM districts ORDER BY district_id');
    const villagesRes = await client.query('SELECT village_id, name, district_id FROM villages ORDER BY village_id');

    console.log(`Fetched ${districtsRes.rows.length} districts and ${villagesRes.rows.length} villages.`);

    const years = [
      { year: '2023-2024', predicted: false },
      { year: '2024-2025', predicted: false },
      { year: '2025-2026', predicted: true },
      { year: '2026-2027', predicted: true }
    ];

    const categories = ['Safe', 'Semi Critical', 'Critical', 'Over Exploited', 'Saline', 'Hilly Area'];

    let sql = `-- Seed file generated by generate_groundwater_seeds.js\n`;
    sql += `TRUNCATE TABLE groundwater_assessments RESTART IDENTITY CASCADE;\n\n`;

    // 1. Generate for Districts
    sql += `-- 1. District Level Groundwater Assessments\n`;
    sql += `INSERT INTO groundwater_assessments (district_id, assessment_year, is_predicted, extractable_resources_bcm, extraction_all_uses_bcm, rainfall_mm, recharge_bcm, natural_discharges_bcm, category)\nVALUES\n`;

    const districtLines = [];
    districtsRes.rows.forEach(d => {
      // Deterministic generation based on district ID
      const dHash = d.district_id;
      years.forEach((yr, idx) => {
        // Change category slightly over time to show trend
        const catIdx = (dHash + idx) % categories.length;
        const category = categories[catIdx];

        const rainfall = 500 + (dHash * 15 + idx * 30) % 600; // 500 to 1100
        const extractable = 1.0 + (dHash * 0.12 + idx * 0.05) % 2.0; // 1.0 to 3.0 BCM

        let ratio = 0.4;
        if (category === 'Safe') ratio = 0.35 + (dHash % 15) / 100;
        else if (category === 'Semi Critical') ratio = 0.72 + (dHash % 15) / 100;
        else if (category === 'Critical') ratio = 0.92 + (dHash % 7) / 100;
        else if (category === 'Over Exploited') ratio = 1.25 + (dHash % 30) / 100;
        else if (category === 'Saline') ratio = 0.6 + (dHash % 20) / 100;
        else ratio = 0.2; // Hilly Area

        const extraction = extractable * ratio;
        const recharge = extractable * 1.1;
        const naturalDischarges = recharge * 0.09;

        districtLines.push(`    (${d.district_id}, '${yr.year}', ${yr.predicted}, ${extractable.toFixed(2)}, ${extraction.toFixed(2)}, ${rainfall.toFixed(2)}, ${recharge.toFixed(2)}, ${naturalDischarges.toFixed(2)}, '${category}')`);
      });
    });

    sql += districtLines.join(',\n') + ';\n\n';

    // 2. Generate for Villages
    sql += `-- 2. Village Level Groundwater Assessments\n`;
    sql += `INSERT INTO groundwater_assessments (village_id, assessment_year, is_predicted, extractable_resources_bcm, extraction_all_uses_bcm, rainfall_mm, recharge_bcm, natural_discharges_bcm, category)\nVALUES\n`;

    const villageLines = [];
    villagesRes.rows.forEach(v => {
      const vHash = v.village_id + v.district_id * 3;
      years.forEach((yr, idx) => {
        const catIdx = (vHash + idx) % categories.length;
        const category = categories[catIdx];

        const rainfall = 450 + (vHash * 8 + idx * 25) % 700; // 450 to 1150
        const extractable = 0.01 + (vHash * 0.002 + idx * 0.001) % 0.04; // 0.01 to 0.05 BCM (1000 to 5000 ham)

        let ratio = 0.4;
        if (category === 'Safe') ratio = 0.4 + (vHash % 10) / 100;
        else if (category === 'Semi Critical') ratio = 0.75 + (vHash % 10) / 100;
        else if (category === 'Critical') ratio = 0.95 + (vHash % 5) / 100;
        else if (category === 'Over Exploited') ratio = 1.35 + (vHash % 25) / 100;
        else if (category === 'Saline') ratio = 0.55 + (vHash % 15) / 100;
        else ratio = 0.15; // Hilly Area

        const extraction = extractable * ratio;
        const recharge = extractable * 1.08;
        const naturalDischarges = recharge * 0.085;

        villageLines.push(`    (${v.village_id}, '${yr.year}', ${yr.predicted}, ${extractable.toFixed(4)}, ${extraction.toFixed(4)}, ${rainfall.toFixed(2)}, ${recharge.toFixed(4)}, ${naturalDischarges.toFixed(4)}, '${category}')`);
      });
    });

    sql += villageLines.join(',\n') + ';\n';

    const outputPath = path.join(__dirname, '../database/seeds/004_groundwater_assessments_seed.sql');
    fs.writeFileSync(outputPath, sql, 'utf8');
    console.log(`Successfully generated seed SQL at ${outputPath}`);
  } catch (err) {
    console.error('Error during generation:', err);
  } finally {
    await client.end();
  }
}

run();
